// <auto-generated />
using System;
using System.Collections.Generic;
using Brasa.Modules.Ordering.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Brasa.Modules.Ordering.Persistence.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20260816124343_AddOrderXminConcurrencyToken")]
    partial class AddOrderXminConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordering")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Brasa.Modules.Ordering.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CoverCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DiscountKind")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsTakeaway")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid");

                    b.Property<string>("TableLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("orders", "ordering");
                });

            modelBuilder.Entity("Brasa.Modules.Ordering.Domain.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Course")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DiscountKind")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset?>("FiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VatRateFraction")
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "Brasa.Modules.Ordering.Domain.OrderLine.UnitPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_price_currency");

                            b1.Property<long>("MinorUnits")
                                .HasColumnType("bigint")
                                .HasColumnName("unit_price_minor_units");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TenantId");

                    b.ToTable("order_lines", "ordering");
                });

            modelBuilder.Entity("Brasa.Modules.Ordering.Domain.OrderLineModifier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PriceDelta", "Brasa.Modules.Ordering.Domain.OrderLineModifier.PriceDelta#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_delta_currency");

                            b1.Property<long>("MinorUnits")
                                .HasColumnType("bigint")
                                .HasColumnName("price_delta_minor_units");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId");

                    b.HasIndex("TenantId");

                    b.ToTable("order_line_modifiers", "ordering");
                });

            modelBuilder.Entity("Brasa.Modules.Ordering.Domain.OrderLine", b =>
                {
                    b.HasOne("Brasa.Modules.Ordering.Domain.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Brasa.Modules.Ordering.Domain.OrderLineModifier", b =>
                {
                    b.HasOne("Brasa.Modules.Ordering.Domain.OrderLine", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("OrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Brasa.Modules.Ordering.Domain.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Brasa.Modules.Ordering.Domain.OrderLine", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
